name: Bug report
description: Create a report to help us improve
labels: [bug]

body:
  - type: dropdown
    id: project
    attributes:
      label: Affected Project
      description: Which project is this bug in
      multiple: true
      options:
        - Connect4
        - UI
        - Utilities
        - Other

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: bug-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value:
        1. Go to '...'
        
        2. Click on '....'
        
        3. Scroll down to '....'
        
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false

  - type: textarea
    id: bug-additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false

  - type: input
    id: bug-os
    attributes:
      label: Operating system
      description: What operating system do you have?
      placeholder: "e.g. Windows 10 Home"

  - type: input
    id: bug-version
    attributes:
      label: Version
      description: What is the version of your operating system?
      placeholder: "e.g. 22H2 x64"

  - type: input
    id: bug-net
    attributes:
      label: .NET Framework
      description: What version of the .NET Framework do you have?
      placeholder: "e.g. .NET 4.8"
